#!/bin/bash

set +e

if [ -z $1 ]; then
  error "Please set the 'version' variable"
  exit 1
fi

VERSION="$1"

set -e

# the temp folder to store binary file...
mkdir -p binary
rm -rf binary/registry || true

cd `dirname $0`
cur=$PWD

# the temp folder to store distribution source code...
TEMP=`mktemp -d ${TMPDIR-/tmp}/distribution.XXXXXX`
git clone -b $VERSION https://github.com/distribution/distribution.git $TEMP

# add patch redis
cd $TEMP
git apply $cur/redis.patch
cd $cur

cd $TEMP
echo "Patching distribution/distribution to use go modules"
curl -L -o go-mod.patch https://github.com/distribution/distribution/commit/5223c27422cc2c40901fe7e08053e3648b9b3300.patch
git apply go-mod.patch || true
echo "Done... now we can update the aws-sdk-go"
curl -L -o aws-sdk-go.patch https://github.com/distribution/distribution/commit/6f84e87803301f7b844bf7ce09f1be4f3b351831.patch
git apply -v aws-sdk-go.patch || true
cd $cur

echo 'build the registry binary ...'
cp Dockerfile.binary $TEMP
docker build -f $TEMP/Dockerfile.binary -t registry-golang $TEMP

echo 'copy the registry binary to local...'
ID=$(docker create registry-golang)
docker cp $ID:/go/src/github.com/docker/distribution/bin/registry binary/registry

docker rm -f $ID
docker rmi -f registry-golang

echo "Build registry binary success, then to build photon image..."
cd $cur
cp $TEMP/cmd/registry/config-example.yml config.yml
rm -rf $TEMP
